### ISSUE TITLE
Which Pull Request(s) should we pick as a good example of our definition of done?

### ISSUE THREAD

**Issue by iteles** [dwyl/definition-of-done#2]
@nelsonic Or should we pair on some [_dwyl/tudo_](https://github.com/dwyl/tudo) work this week and use that to provide as an example for each point in our definition of done? :blush: 

(Realise the definition of done needs to be finalised first!)

**Comment by nelsonic** [comment]
This one: https://github.com/indexzero/ps-tree/pull/12
For now... highlighting the fact that there's a discussion around what gets done.
But really we need one where documentation is prioritised.

**Comment by iteles** [comment]
<img width="786" alt="perfect-PR" src="https://cloud.githubusercontent.com/assets/4185328/9028359/1804d5f2-396e-11e5-9a27-ffc14fad9f36.png">

**Comment by nelsonic** [comment]
@iteles can you send Dan another gentle reminder around 17:00 GMT
https://twitter.com/dshaw/status/628237150253772801
it will take him **5 mins** _tops_ and would mean a lot to us.

**Comment by iteles** [comment]
https://twitter.com/iteles/status/629322027179057152

<img width="606" alt="tweet-encouraging-merge" src="https://cloud.githubusercontent.com/assets/4185328/9124589/114b1756-3c90-11e5-9d41-d7fc82af2308.png">
