### ISSUE TITLE
Fix Markdown Issues in README.md

### ISSUE THREAD

**Issue by nelsonic** [dwyl/definition-of-done#6]
The [`README.md`](https://github.com/dwyl/definition-of-done/tree/8fc98e9c819ad5d311a7dfda75c72d46121d0247) currently has _several_ Markdown fails:

![definition-of-done-markdown-fails](https://user-images.githubusercontent.com/194400/47889200-a73f0b00-de40-11e8-8429-8c54e0eaa250.png)

If anyone has time to fix them, a PR would be very much appreciated!

**Comment by nelsonic** [comment]
@iteles can this task be _assigned_ to someone who is "between tasks"?

**Comment by nelsonic** [comment]
Still one markdown fail on the sample PR link:
![image](https://user-images.githubusercontent.com/194400/48945136-2ba51b00-ef21-11e8-9223-4e40a3ac8114.png)
The underscores are included in the URL which means it goes to 404 when clicked:
![image](https://user-images.githubusercontent.com/194400/48945182-51322480-ef21-11e8-9271-e2ec07bf2e45.png)

**Comment by iteles** [comment]
Merged, thanks for the catch 👍

**Comment by nelsonic** [comment]
Fixed. ✅ 
Now we can figure out how to _integrate_ this into a unified "Workflow" ... https://github.com/dwyl/hq/issues/434 🙄
